export { default as Home } from './home/Home'
export { default as SignIn } from './auth/SignIn'
export { default as SignUp } from './auth/SignUp'
export { default as ResetPass } from './auth/ResetPass'
export { default as ChangePass } from './auth/ChangePass'
export { default as CheckMail } from './auth/CheckMail'
export { default as Verification } from './auth/Verification'
export { default as PageNotFound } from './error/PageNotFound'